const sampleProducts = [
  // MOBILES
  {
    name: "iPhone 15 Pro Max",
    description: "Latest Apple flagship phone with A17 Pro chip",
    price: 119999,
    originalPrice: 139999,
    category: "Mobiles",
    image: "https://images.unsplash.com/photo-1592286927505-1def25115558?w=400",
    rating: 4.5,
    stock: 45,
    discount: 15,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    description: "Ultimate Android flagship with AI features",
    price: 109999,
    originalPrice: 149999,
    category: "Mobiles",
    image: "https://i.ebayimg.com/images/g/2PYAAOSwtshmoUXN/s-l400.jpg",
    rating: 4.6,
    stock: 38,
    discount: 27,
    isBestDeal: true,
    isFlashDeal: true,
  },
  {
    name: "OnePlus 12",
    description: "Fast and smooth performance with 120Hz display",
    price: 64999,
    originalPrice: 79999,
    category: "Mobiles",
    image: "https://oasis.opstatics.com/content/dam/oasis/page/2023/cn/12/12-black.png",
    rating: 4.3,
    stock: 62,
    discount: 19,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Xiaomi 14",
    description: "Great camera and battery life",
    price: 59999,
    originalPrice: 74999,
    category: "Mobiles",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400",
    rating: 4.2,
    stock: 75,
    discount: 20,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // FURNITURE
  {
    name: "Modern Sofa Set",
    description: "3-seater comfortable sofa with premium fabric",
    price: 24999,
    originalPrice: 49999,
    category: "Furniture",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
    rating: 4.4,
    stock: 12,
    discount: 50,
    isBestDeal: true,
    isFlashDeal: true,
  },
  {
    name: "Wooden Dining Table",
    description: "6-seater dining table with solid wood",
    price: 15999,
    originalPrice: 24999,
    category: "Furniture",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400",
    rating: 4.3,
    stock: 18,
    discount: 36,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Office Chair Pro",
    description: "Ergonomic office chair for long working hours",
    price: 8999,
    originalPrice: 14999,
    category: "Furniture",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
    rating: 4.1,
    stock: 35,
    discount: 40,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // FASHION
  {
    name: "Premium Cotton T-Shirt",
    description: "100% organic cotton t-shirt in various colors",
    price: 499,
    originalPrice: 999,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
    rating: 4.2,
    stock: 150,
    discount: 50,
    isBestDeal: false,
    isFlashDeal: true,
  },
  {
    name: "Casual Jeans",
    description: "Comfortable denim jeans for everyday wear",
    price: 999,
    originalPrice: 1999,
    category: "Fashion",
    image: "https://i.pinimg.com/736x/c6/83/ad/c683ad2b272d35c1c2593d1a55372902.jpg",
    rating: 4.4,
    stock: 120,
    discount: 50,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Formal Shirt",
    description: "Professional formal shirt in blue",
    price: 1299,
    originalPrice: 2499,
    category: "Fashion",
    image: "https://assets.myntassets.com/h_200,w_200,c_fill,g_auto/h_1440,q_100,w_1080/v1/assets/images/22223562/2023/3/3/22c14707-fcf7-457e-9dd0-5b914b8a33f51677867998232CantabilMenNavyBluePoloCollarT-shirt1.jpg",
    rating: 4.3,
    stock: 85,
    discount: 48,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // APPLIANCES
  {
    name: "Front Load Washing Machine",
    description: "8kg capacity with AI wash technology",
    price: 39999,
    originalPrice: 69999,
    category: "Appliances",
    image: "https://www.lg.com/content/dam/channel/wcms/in/images/wm/fhp1412z9b/gallery/FHP1412Z9B-DZ-06.jpg/_jcr_content/renditions/thum-1600x1062.jpeg",
    rating: 4.5,
    stock: 22,
    discount: 43,
    isBestDeal: true,
    isFlashDeal: true,
  },
  {
    name: "Microwave Oven",
    description: "30L capacity convection microwave",
    price: 12999,
    originalPrice: 19999,
    category: "Appliances",
    image: "https://tse4.mm.bing.net/th/id/OIP.02bAJeWCcQVsYuKmlkUwTAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.2,
    stock: 30,
    discount: 35,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Air Purifier Pro",
    description: "HEPA filter air purifier for home",
    price: 18999,
    originalPrice: 34999,
    category: "Appliances",
    image: "https://tse4.mm.bing.net/th/id/OIP.AxTMPro-HelnnrHha7ahTwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.3,
    stock: 25,
    discount: 46,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // ELECTRONICS
  {
    name: "Laptop - Dell XPS 13",
    description: "13-inch FHD display with Intel i7 processor",
    price: 94999,
    originalPrice: 119999,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    rating: 4.6,
    stock: 18,
    discount: 21,
    isBestDeal: true,
    isFlashDeal: true,
  },
  {
    name: "Wireless Headphones",
    description: "Noise cancelling Bluetooth headphones",
    price: 4999,
    originalPrice: 9999,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    rating: 4.4,
    stock: 65,
    discount: 50,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Smart Watch",
    description: "AMOLED display with fitness tracking",
    price: 14999,
    originalPrice: 29999,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
    rating: 4.3,
    stock: 48,
    discount: 50,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // GROCERY
  {
    name: "Premium Basmati Rice",
    description: "1kg pack of premium basmati rice",
    price: 299,
    originalPrice: 399,
    category: "Grocery",
    image: "https://cdn0.woolworths.media/content/wowproductimages/large/155084.jpg",
    rating: 4.5,
    stock: 200,
    discount: 25,
    isBestDeal: false,
    isFlashDeal: true,
  },
  {
    name: "Organic Honey",
    description: "500ml pure organic honey",
    price: 399,
    originalPrice: 599,
    category: "Grocery",
    image: "https://th.bing.com/th/id/OIP.thvZtpP_X1jeI4eDVzxMFgHaHa?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.6,
    stock: 150,
    discount: 33,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Almond Butter",
    description: "250g natural almond butter",
    price: 349,
    originalPrice: 549,
    category: "Grocery",
    image: "https://cheflolaskitchen.com/wp-content/uploads/2023/12/Almond-Butter-5-scaled.jpg",
    rating: 4.4,
    stock: 120,
    discount: 36,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // BEAUTY & TOYS
  {
    name: "Face Cream",
    description: "Anti-aging face cream with vitamin C",
    price: 599,
    originalPrice: 1199,
    category: "Beauty & Toys",
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
    rating: 4.2,
    stock: 90,
    discount: 50,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Bluetooth Speaker Toy",
    description: "Kids-friendly colorful Bluetooth speaker",
    price: 1499,
    originalPrice: 2999,
    category: "Beauty & Toys",
    image: "https://m.media-amazon.com/images/I/81lnrWWei4L._AC_SL1500_.jpg",
    rating: 4.3,
    stock: 60,
    discount: 50,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Makeup Kit",
    description: "Complete makeup kit with 12 items",
    price: 999,
    originalPrice: 2499,
    category: "Beauty & Toys",
    image: "https://tse2.mm.bing.net/th/id/OIP.iJF8NctI0BzprmUd5f3xIQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.4,
    stock: 75,
    discount: 60,
    isBestDeal: true,
    isFlashDeal: true,
  },
  // --- MOBILES ---
  {
    name: "iPhone 15 Pro Max",
    description: "Premium performance with A17 Pro chip and Titanium design",
    price: 119999,
    originalPrice: 139999,
    category: "Mobiles",
    image: "https://images.unsplash.com/photo-1592286927505-1def25115558?w=400",
    rating: 4.5,
    stock: 45,
    discount: 15,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Samsung Galaxy S26 Ultra",
    description: "2026 Flagship with Galaxy AI and 200MP Camera",
    price: 124999,
    originalPrice: 134999,
    category: "Mobiles",
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400",
    rating: 4.9,
    stock: 25,
    discount: 8,
    isBestDeal: false,
    isFlashDeal: true,
  },
  {
    name: "Google Pixel 10 Pro",
    description: "The ultimate AI phone with Tensor G5 chip",
    price: 99999,
    originalPrice: 109999,
    category: "Mobiles",
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400",
    rating: 4.7,
    stock: 30,
    discount: 10,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // --- ELECTRONICS ---
  {
    name: "Sony WH-1000XM6",
    description: "Next-gen noise canceling wireless headphones",
    price: 29990,
    originalPrice: 34990,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    rating: 4.8,
    stock: 120,
    discount: 14,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "MacBook Pro M4 Max",
    description: "Professional power for creators and developers",
    price: 249900,
    originalPrice: 269900,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
    rating: 4.9,
    stock: 15,
    discount: 7,
    isBestDeal: false,
    isFlashDeal: false,
  },
  {
    name: "Apple Watch Series 11",
    description: "Advanced health tracking and blood glucose monitoring",
    price: 45900,
    originalPrice: 49900,
    category: "Electronics",
    image: "https://tse1.mm.bing.net/th/id/OIP.v8bwQLy0rfKWL-oIFe9elAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.6,
    stock: 60,
    discount: 8,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // --- APPLIANCES ---
  {
    name: "Dyson Air Purifier Gen 2",
    description: "HEPA-13 filtration with real-time pollution tracking",
    price: 38500,
    originalPrice: 45000,
    category: "Appliances",
    image: "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/ec/purifiers-subcat/TP10-Sub-category-feature-Captures.jpg?$responsive$&cropPathE=desktop&fit=stretch,1&wid=1920",
    rating: 4.7,
    stock: 22,
    discount: 14,
    isBestDeal: false,
    isFlashDeal: true,
  },
  {
    name: "Samsung Bespoke AI Fridge",
    description: "Smart refrigerator with internal cameras and AI meal plan",
    price: 175000,
    originalPrice: 195000,
    category: "Appliances",
    image: "https://images.samsung.com/is/image/samsung/p6pim/ph/rs90f65dnftc/gallery/ph-rs80f-9-inch-ai-home-rs90f65dnftc-thumb-545500942",
    rating: 4.8,
    stock: 10,
    discount: 10,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Smart Air Fryer Pro 6L",
    description: "Cook with 90% less oil, WiFi enabled controls",
    price: 8999,
    originalPrice: 12999,
    category: "Appliances",
    image: "https://tse2.mm.bing.net/th/id/OIP.Sj5XjO1WNRYSekPt3UYPhgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.5,
    stock: 85,
    discount: 30,
    isBestDeal: true,
    isFlashDeal: true,
  },

  // --- FURNITURE ---
  {
    name: "ErgoSmart Office Chair",
    description: "Self-adjusting lumbar support and breathable mesh",
    price: 18500,
    originalPrice: 24000,
    category: "Furniture",
    image: "https://tse1.mm.bing.net/th/id/OIP.6W2HIMWb8gkhWgiNV766_wHaHa?w=700&h=700&rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.6,
    stock: 40,
    discount: 22,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Minimalist Oak Dining Table",
    description: "Solid oak wood with seating for 6 people",
    price: 45000,
    originalPrice: 55000,
    category: "Furniture",
    image: "https://th.bing.com/th/id/OIP.YeARzcd6q8Isw1tP9BRvAAHaHa?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.4,
    stock: 12,
    discount: 18,
    isBestDeal: false,
    isFlashDeal: false,
  },
  {
    name: "King Size Velvet Bed",
    description: "Luxury velvet upholstery with hydraulic storage",
    price: 65000,
    originalPrice: 80000,
    category: "Furniture",
    image: "https://i5.walmartimages.com/seo/AMERLIFE-King-Size-Platform-Bed-Frame-Velvet-Upholstered-Bed-with-Deep-Button-Tufted-Nailhead-Trim-Wingback-Headboard-No-Box-Spring-Needed-Black_0a463c8d-7c76-4c83-9a10-54a3120090ee.f12753446ad9d608e4e0e6f2d98e6c17.jpeg",
    rating: 4.7,
    stock: 8,
    discount: 18,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // --- FASHION ---
  {
    name: "Nike Air Max 2026",
    description: "Sustainable cushioning for everyday comfort",
    price: 12999,
    originalPrice: 15999,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    rating: 4.8,
    stock: 150,
    discount: 18,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Oversized Denim Jacket",
    description: "Eco-friendly denim with a relaxed 90s fit",
    price: 3499,
    originalPrice: 4999,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=400",
    rating: 4.3,
    stock: 200,
    discount: 30,
    isBestDeal: false,
    isFlashDeal: true,
  },
  {
    name: "Premium Linen Shirt",
    description: "Handcrafted Italian linen for summer comfort",
    price: 2499,
    originalPrice: 3999,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400",
    rating: 4.5,
    stock: 300,
    discount: 37,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // --- GROCERY ---
  {
    name: "Organic Arabica Coffee Beans",
    description: "100% organic beans sourced from Coorg",
    price: 850,
    originalPrice: 999,
    category: "Grocery",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400",
    rating: 4.9,
    stock: 500,
    discount: 15,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Keto Friendly Almond Flour",
    description: "Finely ground, gluten-free baking essential",
    price: 1200,
    originalPrice: 1500,
    category: "Grocery",
    image: "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=400",
    rating: 4.7,
    stock: 120,
    discount: 20,
    isBestDeal: false,
    isFlashDeal: false,
  },

  // --- BEAUTY & TOYS ---
  {
    name: "Advanced Snail Mucin Essence",
    description: "Hydrating serum for glass skin finish",
    price: 1450,
    originalPrice: 1850,
    category: "Beauty & Toys",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400",
    rating: 4.8,
    stock: 80,
    discount: 21,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "LEGO Mars Exploration Kit",
    description: "STEM educational building set for kids 10+",
    price: 5499,
    originalPrice: 6999,
    category: "Beauty & Toys",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
    rating: 4.9,
    stock: 40,
    discount: 21,
    isBestDeal: false,
    isFlashDeal: true,
  },
  {
    name: "Matte Liquid Lipstick Set",
    description: "Long-lasting, smudge-proof 12-shade collection",
    price: 1999,
    originalPrice: 2999,
    category: "Beauty & Toys",
    image: "https://images.unsplash.com/photo-1586776977607-310e9c725c37?w=400",
    rating: 4.4,
    stock: 150,
    discount: 33,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // --- MORE ELECTRONICS ---
  {
    name: "ASUS ROG Zephyrus G16",
    description: "RTX 50-series gaming laptop with OLED display",
    price: 185000,
    originalPrice: 210000,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400",
    rating: 4.8,
    stock: 18,
    discount: 12,
    isBestDeal: false,
    isFlashDeal: false,
  },
  {
    name: "Kindle Paperwhite Gen 6",
    description: "Warm light and waterproof for bedside reading",
    price: 13999,
    originalPrice: 15999,
    category: "Electronics",
    image: "https://media.karousell.com/media/photos/products/2023/8/10/kindle_paperwhite_gen_6_1691672467_4ba8a7ba_progressive.jpg",
    rating: 4.7,
    stock: 55,
    discount: 12,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // --- MORE FASHION ---
  {
    name: "Ray-Ban Smart Glasses",
    description: "Meta integrated voice AI and camera",
    price: 28000,
    originalPrice: 32000,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
    rating: 4.5,
    stock: 35,
    discount: 12,
    isBestDeal: false,
    isFlashDeal: true,
  },
  {
    name: "Leather Messenger Bag",
    description: "Hand-stitched genuine leather for 14-inch laptops",
    price: 4500,
    originalPrice: 6500,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
    rating: 4.6,
    stock: 90,
    discount: 30,
    isBestDeal: true,
    isFlashDeal: false,
  },

  // --- MORE GROCERY ---
  {
    name: "Premium Saffron (1g)",
    description: "Grade-A Kashmiri saffron for cooking and wellness",
    price: 350,
    originalPrice: 500,
    category: "Grocery",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=400",
    rating: 4.9,
    stock: 1000,
    discount: 30,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Cold Pressed Olive Oil",
    description: "Extra virgin olive oil for healthy heart",
    price: 999,
    originalPrice: 1499,
    category: "Grocery",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
    rating: 4.7,
    stock: 250,
    discount: 33,
    isBestDeal: false,
    isFlashDeal: true,
  },

  // --- MORE APPLIANCES ---
  {
    name: "Robot Vacuum Cleaner X2",
    description: "Automatic mopping and dust empty station",
    price: 32000,
    originalPrice: 45000,
    category: "Appliances",
    image: "https://tse4.mm.bing.net/th/id/OIP.Sek9IX7e2p1dbKtKwBOUSwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.6,
    stock: 30,
    discount: 28,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Nespresso Coffee Maker",
    description: "Compact espresso machine with milk frother",
    price: 15999,
    originalPrice: 19999,
    category: "Appliances",
    image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5855/5855422_sd.jpg",
    rating: 4.8,
    stock: 45,
    discount: 20,
    isBestDeal: false,
    isFlashDeal: false,
  },

  // --- MORE BEAUTY & TOYS ---
  {
    name: "Ceramide Night Cream",
    description: "Restorative barrier cream for dry skin",
    price: 899,
    originalPrice: 1200,
    category: "Beauty & Toys",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
    rating: 4.7,
    stock: 180,
    discount: 25,
    isBestDeal: true,
    isFlashDeal: false,
  },
  {
    name: "Magnetic Building Tiles",
    description: "100-piece creative set for toddler development",
    price: 2499,
    originalPrice: 3500,
    category: "Beauty & Toys",
    image: "https://th.bing.com/th/id/OIP.NwSu7Zl5JsTfnWNScTH_AQHaHX?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    rating: 4.9,
    stock: 120,
    discount: 28,
    isBestDeal: true,
    isFlashDeal: false,
  }

];

module.exports = { data: sampleProducts };
